spring.application.name=api-gateway
# Server
server.port=8080

# PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-falling-violet-aphdpvoh-pooler.c-7.us-east-1.aws.neon.tech/api-gateway
spring.datasource.username=neondb_owner
spring.datasource.password=npg_aFu6CIirn4WJ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis (Docker)
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

# JWT
jwt.secret=your-256-bit-secret-key-for-jwt-signing-please-change
jwt.expiration.ms=3600000   # 1 hour

# Rate limiting defaults (tokens per user per second)
rate.limit.user.capacity=100
rate.limit.user.refill=20
rate.limit.ip.capacity=50
rate.limit.ip.refill=10